sudo: required
dist: trusty

language: java
jdk: oraclejdk8

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.m2/

env: GRADLE_OPTS="-Xms1g -Xmx3g"
install: ./gradlew setupCIWorkspace
script: ./gradlew build

notifications:
  email: false
  irc:
    channels:
      - "irc.esper.net#Almura"
    use_notice: true
    skip_join: true
    nick:
      secure: "Tl8EE8vO4TOhbHhjhIxVJIp1oiLUn1PcFbJaKeR4SV8m8Gbtg7Y4DBsI18Q8gpzVQmPp32grPw7UA8XIslerFUSMZva712Vmh5oW1nZvu90pmwk2+9C156klocWhKC7kc8KIzn7NI3DEkOk1UbIXhqdjQpuhlTZ8zDIcDqcVPdI="
    password:
      secure: "OKXw3how8+Zoin8UkbWk0Z7/Bx7p5G7gaKp1FwaHvmsowiybWJjjAUIiFKX64rQ1gZDnkzhsuqDJGKe4+0/byGPXXNfMzUMivh2Q842eEesMwcHEk4yB+dPLIxXiIf6AhAvNBmo2VWamjcikbCUkmZahfr7mXGdjpwpS38QK+Ds="
    template:
      - "[\00313%{repository_name}\017] Build #%{build_number} has \00312%{result}\017"
      - "\00313%{repository_name}\017/\00306${branch} \00314%{commit}\017 \00315%{author}\017: %{build_url}"